name: Test and Deploy
on: [push, workflow_dispatch]
jobs:
  test:
    runs_on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "Testing" # Replace with your actual test command

      - name: End testing
        run: echo "Testing complete!"

  deploy:
    runs_on: ubuntu-latest
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy the application
        run: echo "Deploying application" 